carla:
  host: '127.0.0.1'
  # host: '192.168.1.156'
  port: 2000
  timeout: 30
  passive: False
  synchronous_mode: True
  synchronous_mode_wait_for_vehicle_control_command: False
  fixed_delta_seconds: 0.05
  register_all_sensors: True
  town: 'Town01'
  ego_vehicle:
    role_name: ["hero", "ego_vehicle"]

  # Whether to test the perception module, default open true, close false
  perception_switch: False
  ego_sensors:
    gnss:
      role_name: "gnss-osg"
    imu:
      role_name: "imu-osg"
    lidar:
      role_name: "ray_cast-osg"
    # front_6mm_camera: put in the front of the car, otherwise it will affect the perception
    front_6mm_camera:
      role_name: "rgb-6-osg"
    # front_12mm_camera:
    #   role_name: "rgb-12-osg"